// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gklktfvwubplvcbmzymr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrbGt0ZnZ3dWJwbHZjYm16eW1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MTA1NDgsImV4cCI6MjA2NTk4NjU0OH0.lnxpHnZc51i_z2BlJuu08YSiyKN2_Isil6MYp0_jsFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);